name: Build and Deploy (Continuous Integration)

on: [push, pull_request]

jobs:
  build:
    environment:
      name: main
    env:
      database_hostname=${{secrets.database_hostname}}
      database_port=${{secrets.database_port}}
      database_password=${{secrets.database_password}}
      database_name=${{secrets.database_name}}
      database_username=${{secrets.database_username}}
      fb_type=${{secrets.fb_type}}
      fb_project_id=${{secrets.fb_project_id}}
      fb_private_key_id=${{secrets.fb_private_key_id}}
      fb_private_key=${{secrets.fb_private_key}}
      fb_client_email=${{secrets.fb_client_email}}
      fb_client_id=${{secrets.fb_client_id}}
      fb_auth_uri=${{secrets.fb_auth_uri}}
      fb_token_uri=${{secrets.fb_token_uri}}
      fb_auth_provider_x509_cert_url=${{secrets.fb_auth_provider_x509_cert_url}}
      fb_client_x509_cert_url=${{secrets.fb_client_x509_cert_url}}
      fb_universe_domain=${{secrets.fb_universe_domain}}
      speech_key=${{secrets.speech_key}}
      speech_region=${{secrets.speech_region}}
      runpod_endpoint=${{secrets.runpod_endpoint}}
      runpod_api_key=${{secrets.runpod_api_key}}

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   environment:
  #     name: production
  #   steps:
  #     - name: pulling git repo
  #       uses: actions/checkout@v2
  #     - name: deploying to Heroku
  #       uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
  #         heroku_email: ${{secrets.HEROKU_EMAIL}}

  #     - name: deploy to ubuntu server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{secrets.PROD_HOST}}
  #         username: ${{secrets.PROD_USERNAME}}
  #         password: ${{secrets.PROD_PASSWORD}}
  #         script: |
  #           cd app/src
  #           git pull
  #           echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart api
  #     # login to our ubuntu
  #     # cd /app/src
  #     # git pull
  #     # systemctl restart api