name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build and Deploy (Continuous Integration)"]
    types:
      - completed

jobs:

  build:
    environment:
      name: main

    runs-on: self-hosted

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Pull Docker image
      run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
    - name: Delete Old docker container
      run: sudo docker rm -f ttl-backend || true
    - name: Run Docker Container
      run: sudo docker run -d --env-file .env -p 8000:8000 --name ttl-backend ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
