name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build and Deploy (Continuous Integration)"]
    types:
      - completed

jobs:

  build:
    environment:
      name: main
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      FB_TYPE: ${{secrets.FB_TYPE}}
      FB_PROJECT_ID: ${{secrets.FB_PROJECT_ID}}
      FB_PRIVATE_KEY_ID: ${{secrets.FB_PRIVATE_KEY_ID}}
      FB_PRIVATE_KEY: ${{secrets.FB_PRIVATE_KEY}}
      FB_CLIENT_EMAIL: ${{secrets.FB_CLIENT_EMAIL}}
      FB_CLIENT_ID: ${{secrets.FB_CLIENT_ID}}
      FB_AUTH_URI: ${{secrets.FB_AUTH_URI}}
      FB_TOKEN_URI: ${{secrets.FB_TOKEN_URI}}
      FB_AUTH_PROVIDER_X509_CERT_URL: ${{secrets.FB_AUTH_PROVIDER_X509_CERT_URL}}
      FB_CLIENT_X509_CERT_URL: ${{secrets.FB_CLIENT_X509_CERT_URL}}
      FB_UNIVERSE_DOMAIN: ${{secrets.FB_UNIVERSE_DOMAIN}}
      SPEECH_KEY: ${{secrets.SPEECH_KEY}}
      SPEECH_REGION: ${{secrets.SPEECH_REGION}}
      RUNPOD_ENDPOINT: ${{secrets.RUNPOD_ENDPOINT}}
      RUNPOD_API_KEY: ${{secrets.RUNPOD_API_KEY}}

    runs-on: self-hosted

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Pull Docker image
      run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
    - name: Delete Old docker container
      run: sudo docker rm -f ttl-backend || true
    - name: List files in the current directory
      run: ls -la
    - name: Run Docker Container
      run: sudo docker run -d --env-file .env -p 8000:8000 --name ttl-backend ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest
